{% set name = "dessinemoi" %}
{% set version = "22.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dessinemoi-{{ version }}.tar.gz
  sha256: 7f3a7ca70200e3d189d2e8d17e7480f01182fe7d30a6b7d4f66d8fa581eb43ad

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip <22.2  # Build breaks otherwise
    - python >=3.7
    - pdm
  run:
    - attrs >=21
    - python >=3.7

test:
  imports:
    - dessinemoi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leroyvn/dessinemoi
  doc_url: https://dessinemoi.readthedocs.io
  license: MIT
  license_file:
    - LICENSE
  summary: A simple Python factory system
  description: |
    Dessine-moi is a simple Python implementation of the factory pattern. It was
    born from the need to create dynamically object trees from nested
    dictionaries (e.g. a JSON document).


extra:
  recipe-maintainers:
    - leroyvn
