{% set name = "dessinemoi" %}
{% set version = "24.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dessinemoi-{{ version }}.tar.gz
  sha256: d81feb5fc66ec660351891c0ccc10c2a87ff49da4adfd1029656dd0ba17449c5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - attrs >=21

test:
  imports:
    - dessinemoi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rayference/dessinemoi
  doc_url: https://dessinemoi.readthedocs.io
  summary: A simple Python factory system
  license: MIT
  license_file: LICENSE
  description: |
    Dessine-moi is a simple Python implementation of the factory pattern. It was
    born from the need to create dynamically object trees from nested
    dictionaries (e.g. a JSON document).


extra:
  recipe-maintainers:
    - leroyvn
