{% set name = "dessinemoi" %}
{% set version = "23.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dessinemoi-{{ version }}.tar.gz
  sha256: bfdca9f754260ae7c6e423722266666e743aac34523ad49a8fac970ee0ffebf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pdm-pep517
    - pip
  run:
    - python >=3.8
    - attrs >=21

test:
  imports:
    - dessinemoi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leroyvn/dessinemoi
  doc_url: https://dessinemoi.readthedocs.io
  license: MIT
  license_file:
    - LICENSE
  summary: A simple Python factory system
  description: |
    Dessine-moi is a simple Python implementation of the factory pattern. It was
    born from the need to create dynamically object trees from nested
    dictionaries (e.g. a JSON document).


extra:
  recipe-maintainers:
    - leroyvn
