{% set name = "pinttrs" %}
{% set version = "21.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pinttrs-{{ version }}.tar.gz
  sha256: 7fad4712db2a6a769b7b4455b9dbd38a54f1771fec4757cbe47d7fd6ede5efff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - attrs
    - pint
    - python

test:
  imports:
    - pinttr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leroyvn/pinttrs
  doc_url: https://pinttrs.readthedocs.io
  license: MIT
  summary: Pint meets attrs
  description: |
    The amazing attrs library is a game-changer when it comes to writing classes.
    Its initialisation sequence notably allows for automated conversion and
    verification of attribute values. This package is an attempt at designing a
    system to apply units automatically and reliably to attributes with Pint.

extra:
  recipe-maintainers:
    - leroyvn
