{% set name = "pinttrs" %}
{% set version = "21.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pinttrs-{{ version }}.tar.gz
  sha256: c9817914fd6981ab1b7d83e93aaa36d98b07d311a5b543c67752189d5750b767

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - attrs
    - pint
    - python

test:
  imports:
    - pinttr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/leroyvn/pinttrs
  doc_url: https://pinttrs.readthedocs.io
  license: MIT
  summary: Pint meets attrs
  description: |
    The amazing attrs library is a game-changer when it comes to writing classes.
    Its initialisation sequence notably allows for automated conversion and
    verification of attribute values. This package is an attempt at designing a
    system to apply units automatically and reliably to attributes with Pint.

extra:
  recipe-maintainers:
    - leroyvn
