{% set name = "aabbtree" %}
{% set version = "2.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aabbtree-{{ version }}.tar.gz
  sha256: dec509bdf12c07819e5f9de226f2dbb62eae8f376d5aebb82929905a84738e92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - aabbtree
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kip-hart/AABBTree
  doc_url: https://aabbtree.readthedocs.io/
  summary: Pure Python implementation of d-dimensional AABB tree.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - leroyvn
